
baseURL = "//jacobscorner.tech"
defaultContentLanguage = "en"
theme = "hermit-v2"
#enableRobotsTXT = true ## set to true to enable inbuilt robots.txt

#[languages]
#  [languages.en]
#    title = 'CHANGE ME'
#    [languages.en.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 1
#  [languages.fr]
#    title = 'CHANGE ME(FR)'
#    [languages.fr.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 2
#  [languages.it]
#    title = 'CHANGE ME(IT)'
#    [languages.it.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 3
 
languageCode = "en-gb"

title = "Jacob's Tech Corner"

pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

enableEmoji = true

#[services]
#  [services.disqus]
#    shortname = ''
#  [services.googleAnalytics]
#    id = ''

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]


[params.author]
  name = "Jacob Andrews-Murphy"

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

[params]
  dateform        = "January 2, 2006"
  dateformShort   = "02-01-2006"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "A collection of techinal thinking, by Jacob Andrews-Murphy"
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "A collection of technological thinking"
  footerCopyright = "Jacob Andrews-Murphy"
  footerHideThemeName = true

  justifyContent = true

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "| "
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # descriptionInPosts= true
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  # usesAnimation = true
  
  [[params.socialLinks]]
    name = "bluesky"
    url = "https://bsky.app/profile/jacob.andrewsmurphy.online"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/jacobtmurph"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "Setups"
    url = "setups/"
    weight = 10